title: unique finds for kids
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9795797746628523
  brandStrength: 0.5399564011022449
  lightness: 0.3363335344474763
  brandColors:
    - '#020101'
    - '#413A1F'
    - '#91895C'
    - '#6E7717'
    - '#A5AC0F'
  rhythmicContrast: 0.712245944654569
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: slugsbugsandrobots
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3006902583874762
layout_spectrum: 0.3806025849189609
