name: slugsbugsandrobots
favicon: null
layout_spectrum: 0.62918
typography_spectrum: 0.08457
title: fun finds for little ones
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020101'
    - '#413A1F'
    - '#91895C'
    - '#6E7717'
    - '#A5AC0F'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
